steps:
  - label: windows-test
    commands:
      - yarn install --frozen-lockfile --non-interactive --network-timeout 500000
      - yarn webdriver-update-appveyor
      - node --version
      - yarn --version
      - bazel test ...
      - yarn test
      - node tests\legacy-cli\run_e2e.js --appveyor "--glob=tests/{basic,commands,generate,build/styles}/**"
    plugins:
      - docker#v2.1.0:
          image: "filipesilva/node-bazel-windows:0.0.2"
    agents:
      windows: true
